# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCompradeArticulos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_compradeArticulos(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.find_element(By.LINK_TEXT, "Samsung galaxy s7").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
    self.driver.find_element(By.ID, "nava").click()
    self.driver.find_element(By.LINK_TEXT, "Laptops").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4:nth-child(6) .card-img-top").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    self.driver.find_element(By.ID, "myTabContent").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Manuel Alejandro Vargas Rodríguez")
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.ID, "country").send_keys("Colombia")
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "city").send_keys("Bogotá")
    self.driver.find_element(By.ID, "card").click()
    self.driver.find_element(By.ID, "card").send_keys("Visa")
    self.driver.find_element(By.ID, "month").click()
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "month").click()
    self.driver.find_element(By.ID, "month").send_keys("12")
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys("2032")
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
  
